# Generated by Django 3.1.3 on 2020-11-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_remove_geolocation_local_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='user',
        ),
    ]
