# Generated by Django 3.1.3 on 2020-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_remove_geolocation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
