# Generated by Django 3.1.3 on 2020-11-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0006_auto_20201110_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userurl',
            old_name='user',
            new_name='owner',
        ),
    ]
