# Generated by Django 3.1.3 on 2020-11-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0007_auto_20201110_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userurl',
            old_name='owner',
            new_name='user',
        ),
    ]
