# Generated by Django 3.1.3 on 2020-11-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0009_auto_20201110_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userurl',
            name='last_modified',
        ),
    ]
