# Generated by Django 3.1.3 on 2020-12-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='slug',
        ),
    ]
