# Generated by Django 3.1.3 on 2020-12-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_membership_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='temp_link',
        ),
        migrations.AddField(
            model_name='membership',
            name='allow_viewing_original_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='basic_photo_height',
            field=models.IntegerField(choices=[(100, 100), (200, 200), (400, 400), (500, 500), (800, 800), (1024, 1024), (2048, 2048), (4096, 4096)], default=400),
        ),
        migrations.AddField(
            model_name='membership',
            name='generating_temp_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='premium_photo_height',
            field=models.IntegerField(choices=[(100, 100), (200, 200), (400, 400), (500, 500), (800, 800), (1024, 1024), (2048, 2048), (4096, 4096)], default=400),
        ),
    ]
