# Generated by Django 3.1.3 on 2020-12-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20201211_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='allow_viewing_basic_image',
        ),
    ]
