# Generated by Django 3.1.3 on 2020-12-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201210_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='basic_image',
            new_name='enterprise_image',
        ),
    ]
