# Generated by Django 3.1.3 on 2020-12-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20201211_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='basic_image',
        ),
    ]
